/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as LuuTruRouteImport } from './routes/luu-tru'
import { Route as TheGioiRouteImport } from './routes/the-gioi'
import { Route as TrungTocRouteImport } from './routes/trung-toc'
import { Route as AuthenticatedAdminRouteImport } from './routes/_authenticated/admin'
import { Route as AstraIndexRouteImport } from './routes/astra.index'
import { Route as AstraIdRouteImport } from './routes/astra.$id'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const LuuTruRoute = LuuTruRouteImport.update({
  id: '/luu-tru',
  path: '/luu-tru',
  getParentRoute: () => rootRouteImport,
} as any)
const TheGioiRoute = TheGioiRouteImport.update({
  id: '/the-gioi',
  path: '/the-gioi',
  getParentRoute: () => rootRouteImport,
} as any)
const TrungTocRoute = TrungTocRouteImport.update({
  id: '/trung-toc',
  path: '/trung-toc',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedAdminRoute = AuthenticatedAdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AstraIndexRoute = AstraIndexRouteImport.update({
  id: '/astra/',
  path: '/astra/',
  getParentRoute: () => rootRouteImport,
} as any)
const AstraIdRoute = AstraIdRouteImport.update({
  id: '/astra/$id',
  path: '/astra/$id',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/luu-tru': typeof LuuTruRoute
  '/the-gioi': typeof TheGioiRoute
  '/trung-toc': typeof TrungTocRoute
  '/admin': typeof AuthenticatedAdminRoute
  '/astra/$id': typeof AstraIdRoute
  '/astra/': typeof AstraIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/luu-tru': typeof LuuTruRoute
  '/the-gioi': typeof TheGioiRoute
  '/trung-toc': typeof TrungTocRoute
  '/admin': typeof AuthenticatedAdminRoute
  '/astra/$id': typeof AstraIdRoute
  '/astra': typeof AstraIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/auth': typeof AuthRoute
  '/luu-tru': typeof LuuTruRoute
  '/the-gioi': typeof TheGioiRoute
  '/trung-toc': typeof TrungTocRoute
  '/_authenticated/admin': typeof AuthenticatedAdminRoute
  '/astra/$id': typeof AstraIdRoute
  '/astra/': typeof AstraIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/luu-tru'
    | '/the-gioi'
    | '/trung-toc'
    | '/admin'
    | '/astra/$id'
    | '/astra/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/luu-tru'
    | '/the-gioi'
    | '/trung-toc'
    | '/admin'
    | '/astra/$id'
    | '/astra'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/auth'
    | '/luu-tru'
    | '/the-gioi'
    | '/trung-toc'
    | '/_authenticated/admin'
    | '/astra/$id'
    | '/astra/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  AuthRoute: typeof AuthRoute
  LuuTruRoute: typeof LuuTruRoute
  TheGioiRoute: typeof TheGioiRoute
  TrungTocRoute: typeof TrungTocRoute
  AstraIdRoute: typeof AstraIdRoute
  AstraIndexRoute: typeof AstraIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/luu-tru': {
      id: '/luu-tru'
      path: '/luu-tru'
      fullPath: '/luu-tru'
      preLoaderRoute: typeof LuuTruRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/the-gioi': {
      id: '/the-gioi'
      path: '/the-gioi'
      fullPath: '/the-gioi'
      preLoaderRoute: typeof TheGioiRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/trung-toc': {
      id: '/trung-toc'
      path: '/trung-toc'
      fullPath: '/trung-toc'
      preLoaderRoute: typeof TrungTocRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/admin': {
      id: '/_authenticated/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AuthenticatedAdminRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/astra/': {
      id: '/astra/'
      path: '/astra'
      fullPath: '/astra/'
      preLoaderRoute: typeof AstraIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/astra/$id': {
      id: '/astra/$id'
      path: '/astra/$id'
      fullPath: '/astra/$id'
      preLoaderRoute: typeof AstraIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface AuthenticatedRouteRouteChildren {
  AuthenticatedAdminRoute: typeof AuthenticatedAdminRoute
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedAdminRoute: AuthenticatedAdminRoute,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  AuthRoute: AuthRoute,
  LuuTruRoute: LuuTruRoute,
  TheGioiRoute: TheGioiRoute,
  TrungTocRoute: TrungTocRoute,
  AstraIdRoute: AstraIdRoute,
  AstraIndexRoute: AstraIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
